version: '2'
services:
  taskinator-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/taskinator/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=taskinator
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
